# Generated by Django 4.2.27 on 2026-01-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('roads', 'Дороги'), ('housing', 'ЖКХ'), ('ecology', 'Экология'), ('transport', 'Транспорт'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
