# Generated by Django 4.2.27 on 2026-01-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'На рассмотрении'), ('done', 'Решено')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('roads', 'Дороги'), ('housing', 'ЖКХ'), ('transport', 'Транспорт'), ('ecology', 'Экология'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
