# Generated by Django 4.2.27 on 2026-01-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_status_alter_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(blank=True, choices=[('roads', 'Дороги'), ('housing', 'ЖКХ'), ('transport', 'Транспорт'), ('ecology', 'Экология'), ('other', 'Другое')], default='other', max_length=100, null=True),
        ),
    ]
